// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7a2TB4xm3WEkmEX07xf30BFMV7EPOEPU',
    appId: '1:873079511287:web:7ed3ffcdc08e66ac3b1bf2',
    messagingSenderId: '873079511287',
    projectId: 'lettucewatch-ab76c',
    authDomain: 'lettucewatch-ab76c.firebaseapp.com',
    databaseURL: 'https://lettucewatch-ab76c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lettucewatch-ab76c.appspot.com',
    measurementId: 'G-M8QLMM5J6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTw4OPBNceGg1FpTkuR-r_QXcldWiwos',
    appId: '1:873079511287:android:77db90a67abc39253b1bf2',
    messagingSenderId: '873079511287',
    projectId: 'lettucewatch-ab76c',
    databaseURL: 'https://lettucewatch-ab76c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lettucewatch-ab76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoO4Kiu9TufNRfRTbHKFTpm1-uBg9GruU',
    appId: '1:873079511287:ios:ab1ef6d0dfb16e763b1bf2',
    messagingSenderId: '873079511287',
    projectId: 'lettucewatch-ab76c',
    databaseURL: 'https://lettucewatch-ab76c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lettucewatch-ab76c.appspot.com',
    iosClientId: '873079511287-lqcar903vee11chda4aa887r33uc4sj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettucewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoO4Kiu9TufNRfRTbHKFTpm1-uBg9GruU',
    appId: '1:873079511287:ios:a315f148311b41c43b1bf2',
    messagingSenderId: '873079511287',
    projectId: 'lettucewatch-ab76c',
    databaseURL: 'https://lettucewatch-ab76c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lettucewatch-ab76c.appspot.com',
    iosClientId: '873079511287-5t0c7vgv19ksgou9fsqqgmo5k3eb2erc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettucewatch.RunnerTests',
  );
}
